'use client';
import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import MarketTicker from '@/components/MarketTicker';
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend
} from 'recharts';

const BRAND_GOLD = '#FCD535';
const BG_DARK = '#1E1E1E'; 
const PANEL_BG = '#242424'; 
const BORDER_COLOR = '#2E2E2E'; 

// بيانات وهمية للأرباح
const revenueData = [
  { name: 'Jan', revenue: 400 },
  { name: 'Feb', revenue: 1200 },
  { name: 'Mar', revenue: 900 },
  { name: 'Apr', revenue: 2400 },
  { name: 'May', revenue: 3800 },
  { name: 'Jun', revenue: 6500 },
];

const activitySourceData = [
  { name: 'Direct Mints (30%)', value: 65 },  
  { name: 'Trading Fees (10%)', value: 25 },  
  { name: 'Bonuses', value: 10 },             
];

const COLORS = [BRAND_GOLD, '#FFFFFF', '#666666'];

export default function AffiliatePage() {
  const { address, isConnected } = useAccount();
  const [referralLink, setReferralLink] = useState('');
  const [isCopied, setIsCopied] = useState(false);
  const [mounted, setMounted] = useState(false);

  // Pagination States
  const [ledgerPage, setLedgerPage] = useState(1);
  const [payoutPage, setPayoutPage] = useState(1);

  useEffect(() => {
      setMounted(true);
      if (address) {
          const origin = typeof window !== 'undefined' && window.location.origin ? window.location.origin : '';
          setReferralLink(`${origin}/mint?ref=${address}`);
      }
  }, [address]);

  const copyLink = () => {
      navigator.clipboard.writeText(referralLink);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
  };

  if (!mounted) return null;

  return (
    <main style={{ backgroundColor: BG_DARK, minHeight: '100vh', paddingBottom: '80px', color: '#fff', fontFamily: 'sans-serif' }}>
        
        {/* 1. TICKER */}
        <div style={{ marginTop: '0px' }}>
            <MarketTicker />
        </div>

        {/* HERO SECTION */}
        <div className="container pt-5">
            <div className="row justify-content-center text-center mb-5">
                <div className="col-lg-10">
                    <h6 className="text-uppercase tracking-widest mb-3" style={{ color: '#888', letterSpacing: '3px', fontSize: '11px' }}>Institutional Partner Program</h6>
                    <h1 className="fw-bold mb-3" style={{ fontSize: '3rem', color: '#E0E0E0', letterSpacing: '-1px' }}>
                        NNM <span style={{ color: BRAND_GOLD }}>Alliance</span>
                    </h1>
                    <p style={{ color: '#B0B0B0', maxWidth: '700px', margin: '0 auto', lineHeight: '1.6', fontSize: '15px' }}>
                        Build a sustainable revenue stream. Earn <span style={{ color: '#fff' }}>30% instant commission</span> on mints, plus <span style={{ color: '#fff' }}>10% lifetime royalties</span> on all future trading fees generated by your referred users.
                    </p>
                </div>
            </div>

            {!isConnected ? (
                <div className="d-flex justify-content-center align-items-center" style={{ height: '40vh' }}>
                    <div className="p-5 rounded-4 text-center" style={{ border: `1px solid ${BORDER_COLOR}`, background: PANEL_BG }}>
                        <i className="bi bi-wallet2 mb-3 d-block" style={{ fontSize: '30px', color: BRAND_GOLD }}></i>
                        <h3 className="h5 mb-4 text-white">Connect Wallet to Access Dashboard</h3>
                        <ConnectButton />
                    </div>
                </div>
            ) : (
                <div className="fade-in-up">
                    
                    {/* 2. REFERRAL LINK BAR */}
                    <div className="p-4 rounded-3 mb-5 d-flex flex-column flex-md-row align-items-center justify-content-between gap-4 glass-panel">
                        <div className="d-flex align-items-center gap-3 w-100">
                            <div className="icon-circle"><i className="bi bi-link-45deg"></i></div>
                            <div className="flex-grow-1">
                                <label style={{ fontSize: '10px', textTransform: 'uppercase', color: '#888', letterSpacing: '1px' }}>Your Exclusive Link</label>
                                <div className="d-flex align-items-center gap-2 mt-1">
                                    <code style={{ color: BRAND_GOLD, fontSize: '15px', background: 'transparent' }}>{referralLink}</code>
                                </div>
                            </div>
                        </div>
                        <button onClick={copyLink} className="btn-gold-outline">
                            {isCopied ? 'COPIED' : 'COPY LINK'}
                        </button>
                    </div>

                    {/* 3. KEY METRICS (STATS) - معدل حسب طلبك */}
                    <div className="row g-3 mb-4">
                        
                        {/* Card 1: Total Revenue (الإجمالي الكلي) */}
                        <div className="col-md-3">
                            <div className="stat-card h-100 position-relative">
                                <div className="d-flex justify-content-between align-items-start mb-2">
                                    <div className="stat-icon"><i className="bi bi-bank"></i></div>
                                    <span className="trend-badge">+12%</span>
                                </div>
                                <div className="stat-value">$6,500.00</div>
                                <div className="stat-label">Total Lifetime Revenue</div>
                            </div>
                        </div>

                        {/* Card 2: Active Users (النشطون) */}
                        <div className="col-md-3">
                            <div className="stat-card h-100 position-relative">
                                <div className="d-flex justify-content-between align-items-start mb-2">
                                    <div className="stat-icon"><i className="bi bi-people"></i></div>
                                    {/* الرقم الصغير بجوار الأيقونة */}
                                    <div className="stat-count-badge">142 Users</div>
                                </div>
                                {/* الرقم الكبير يمثل العائد المادي */}
                                <div className="stat-value">$1,200.00</div>
                                <div className="stat-label">Royalty Earnings (10%)</div>
                            </div>
                        </div>

                        {/* Card 3: Assets Minted (الطباعة) */}
                        <div className="col-md-3">
                            <div className="stat-card h-100 position-relative">
                                <div className="d-flex justify-content-between align-items-start mb-2">
                                    <div className="stat-icon"><i className="bi bi-diamond"></i></div>
                                    {/* الرقم الصغير بجوار الأيقونة */}
                                    <div className="stat-count-badge">48 Mints</div>
                                </div>
                                {/* الرقم الكبير يمثل العائد المادي */}
                                <div className="stat-value">$4,050.00</div>
                                <div className="stat-label">Mint Commission (30%)</div>
                            </div>
                        </div>

                        {/* Card 4: Pending Payout (في انتظار الدفع) */}
                        <div className="col-md-3">
                            <div className="stat-card h-100 position-relative" style={{ border: `1px solid ${BRAND_GOLD}44` }}>
                                <div className="d-flex justify-content-between align-items-start mb-2">
                                    <div className="stat-icon" style={{ color: BRAND_GOLD }}><i className="bi bi-wallet2"></i></div>
                                    <span className="status-dot"></span>
                                </div>
                                <div className="stat-value" style={{ color: BRAND_GOLD }}>$1,250.00</div>
                                <div className="stat-label">Unpaid Balance</div>
                            </div>
                        </div>

                    </div>

                    {/* 4. CHARTS SECTION */}
                    <div className="row g-3 mb-5">
                        <div className="col-lg-8">
                            <div className="chart-panel h-100">
                                <div className="panel-header">
                                    <h5 className="panel-title">Revenue Performance</h5>
                                    <div className="panel-actions">
                                        <span className="active">1M</span>
                                        <span>3M</span>
                                        <span>1Y</span>
                                    </div>
                                </div>
                                <div style={{ height: '300px', width: '100%' }}>
                                    <ResponsiveContainer width="100%" height="100%">
                                        <AreaChart data={revenueData}>
                                            <defs>
                                                <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                                                    <stop offset="5%" stopColor={BRAND_GOLD} stopOpacity={0.2}/>
                                                    <stop offset="95%" stopColor={BRAND_GOLD} stopOpacity={0}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                                            <XAxis dataKey="name" stroke="#666" fontSize={11} tickLine={false} axisLine={false} />
                                            <YAxis stroke="#666" fontSize={11} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} />
                                            <Tooltip 
                                                contentStyle={{ backgroundColor: '#242424', border: `1px solid ${BORDER_COLOR}`, borderRadius: '8px', color: '#fff' }}
                                                itemStyle={{ color: BRAND_GOLD }}
                                            />
                                            <Area type="monotone" dataKey="revenue" stroke={BRAND_GOLD} strokeWidth={2} fillOpacity={1} fill="url(#colorRev)" />
                                        </AreaChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                        </div>

                        <div className="col-lg-4">
                            <div className="chart-panel h-100">
                                <div className="panel-header mb-4">
                                    <h5 className="panel-title">Earnings Source</h5>
                                </div>
                                <div style={{ height: '260px', width: '100%', position: 'relative' }}>
                                    <ResponsiveContainer width="100%" height="100%">
                                        <PieChart>
                                            <Pie
                                                data={activitySourceData}
                                                cx="50%"
                                                cy="50%"
                                                innerRadius={60}
                                                outerRadius={90}
                                                paddingAngle={5}
                                                dataKey="value"
                                                stroke="none"
                                            >
                                                {activitySourceData.map((entry, index) => (
                                                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                                ))}
                                            </Pie>
                                            <Tooltip 
                                                contentStyle={{ backgroundColor: '#242424', border: '1px solid #333', borderRadius: '8px', color: '#fff' }}
                                            />
                                            <Legend verticalAlign="bottom" height={36} iconType="triangle" />
                                        </PieChart>
                                    </ResponsiveContainer>
                                    <div style={{ position: 'absolute', top: '45%', left: '50%', transform: 'translate(-50%, -50%)', textAlign: 'center' }}>
                                        <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#fff' }}>100%</div>
                                        <div style={{ fontSize: '10px', color: '#888' }}>Total Yield</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* 5. TRANSACTION LEDGER (سجل العمليات - الدخل) */}
                    <div className="chart-panel mb-4">
                        <div className="panel-header mb-3">
                            <h5 className="panel-title">Transaction Ledger (Earnings)</h5>
                            <button className="btn-icon"><i className="bi bi-download"></i> CSV</button>
                        </div>
                        <div className="table-responsive">
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th>TIMESTAMP</th>
                                        <th>TYPE</th>
                                        <th>SOURCE WALLET</th>
                                        <th>ASSET</th>
                                        <th>TX AMOUNT</th>
                                        <th className="text-end">EARNINGS</th>
                                        <th className="text-end">STATUS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {[1, 2, 3, 4, 5].map((_, i) => (
                                        <tr key={i}>
                                            <td style={{ color: '#666' }}>2025-01-1{i} 14:30</td>
                                            <td><span className="type-badge">MINT</span></td>
                                            <td style={{ fontFamily: 'monospace', color: '#888' }}>0x71C...9A2{i}</td>
                                            <td>NNM #{1020 + i}</td>
                                            <td>$50.00</td>
                                            <td className="text-end" style={{ color: BRAND_GOLD, fontWeight: 'bold' }}>+$15.00</td>
                                            <td className="text-end"><span className="status-badge pending">UNPAID</span></td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        {/* Pagination */}
                        <div className="d-flex justify-content-end align-items-center gap-3 mt-3 px-2">
                            <button className="btn-pagination" disabled={ledgerPage === 1} onClick={() => setLedgerPage(p => p - 1)}><i className="bi bi-chevron-left"></i></button>
                            <span style={{ fontSize: '12px', color: '#666' }}>Page {ledgerPage}</span>
                            <button className="btn-pagination" onClick={() => setLedgerPage(p => p + 1)}><i className="bi bi-chevron-right"></i></button>
                        </div>
                    </div>

                    {/* 6. PAYOUT HISTORY (سجل التحويلات - المدفوعات) */}
                    <div className="chart-panel">
                        <div className="panel-header mb-3">
                            <h5 className="panel-title">Payout History (Withdrawals)</h5>
                        </div>
                        <div className="table-responsive">
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th>PAYOUT DATE</th>
                                        <th>TRANSACTION HASH</th>
                                        <th>METHOD</th>
                                        <th className="text-end">AMOUNT PAID</th>
                                        <th className="text-end">STATUS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {[1, 2].map((_, i) => (
                                        <tr key={i}>
                                            <td style={{ color: '#666' }}>2024-12-0{i+5} 09:00</td>
                                            <td style={{ fontFamily: 'monospace', color: BRAND_GOLD }}>
                                                <a href="#" className="text-decoration-none" style={{ color: 'inherit' }}>0xabc...def{i} <i className="bi bi-box-arrow-up-right ms-1" style={{ fontSize: '10px' }}></i></a>
                                            </td>
                                            <td><span style={{ fontSize: '11px', color: '#aaa' }}>USDT Transfer</span></td>
                                            <td className="text-end" style={{ color: '#fff', fontWeight: 'bold' }}>$500.00</td>
                                            <td className="text-end"><span className="status-badge success">COMPLETED</span></td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        {/* Pagination */}
                        <div className="d-flex justify-content-end align-items-center gap-3 mt-3 px-2">
                            <button className="btn-pagination" disabled={payoutPage === 1} onClick={() => setPayoutPage(p => p - 1)}><i className="bi bi-chevron-left"></i></button>
                            <span style={{ fontSize: '12px', color: '#666' }}>Page {payoutPage}</span>
                            <button className="btn-pagination" onClick={() => setPayoutPage(p => p + 1)}><i className="bi bi-chevron-right"></i></button>
                        </div>
                    </div>

                </div>
            )}
        </div>

        <style jsx>{`
            .glass-panel {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                box-shadow: 0 4px 20px rgba(0,0,0,0.2);
            }
            .icon-circle {
                width: 40px; height: 40px;
                border-radius: 50%;
                background: rgba(252, 213, 53, 0.1);
                color: ${BRAND_GOLD};
                display: flex; align-items: center; justify-content: center;
                font-size: 18px;
            }
            .btn-gold-outline {
                background: transparent;
                border: 1px solid ${BRAND_GOLD};
                color: ${BRAND_GOLD};
                padding: 10px 24px;
                border-radius: 6px;
                font-size: 12px;
                font-weight: 700;
                letter-spacing: 1px;
                transition: all 0.3s;
            }
            .btn-gold-outline:hover {
                background: ${BRAND_GOLD};
                color: #000;
                box-shadow: 0 0 15px rgba(252, 213, 53, 0.3);
            }

            /* Stats Cards */
            .stat-card {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                border-radius: 12px;
                padding: 20px;
                position: relative;
                overflow: hidden;
            }
            .stat-icon { color: #666; font-size: 20px; }
            .stat-count-badge { font-size: 11px; color: ${BRAND_GOLD}; background: rgba(252, 213, 53, 0.1); padding: 2px 6px; border-radius: 4px; font-weight: 600; }
            .stat-value { font-size: 24px; font-weight: 700; color: #fff; margin-bottom: 5px; font-family: 'Inter', sans-serif; }
            .stat-label { font-size: 11px; text-transform: uppercase; color: #888; letter-spacing: 1px; }
            .trend-badge { font-size: 10px; color: #4caf50; background: rgba(76, 175, 80, 0.1); padding: 2px 6px; border-radius: 4px; }
            .status-dot { width: 8px; height: 8px; background: ${BRAND_GOLD}; border-radius: 50%; box-shadow: 0 0 10px ${BRAND_GOLD}; }

            /* Charts Panels */
            .chart-panel {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                border-radius: 12px;
                padding: 20px;
            }
            .panel-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid ${BORDER_COLOR}; padding-bottom: 15px; margin-bottom: 15px; }
            .panel-title { font-size: 14px; color: #E0E0E0; margin: 0; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
            .panel-actions span { font-size: 11px; color: #666; cursor: pointer; margin-left: 15px; transition: 0.2s; }
            .panel-actions span.active { color: ${BRAND_GOLD}; font-weight: bold; }
            
            /* Table Styling */
            .table { margin: 0; }
            .table th { background: transparent; color: #666; font-size: 10px; font-weight: 600; letter-spacing: 1px; border-bottom: 1px solid #333; padding-bottom: 15px; }
            .table td { background: transparent; color: #E0E0E0; font-size: 13px; border-bottom: 1px solid #2E2E2E; padding: 15px 0; vertical-align: middle; }
            .table tr:last-child td { border-bottom: none; }
            
            .type-badge { font-size: 9px; padding: 3px 8px; border-radius: 4px; font-weight: bold; background: #222; color: #888; border: 1px solid #333; }
            .status-badge { font-size: 9px; padding: 3px 8px; border-radius: 4px; font-weight: bold; }
            .status-badge.success { color: #4caf50; background: rgba(76, 175, 80, 0.1); }
            .status-badge.pending { color: #ff9800; background: rgba(255, 152, 0, 0.1); }

            .btn-icon { background: transparent; border: 1px solid #333; color: #888; border-radius: 4px; padding: 4px 10px; font-size: 11px; }
            .btn-icon:hover { border-color: #666; color: #fff; }

            .btn-pagination { background: transparent; border: 1px solid #333; color: #888; width: 28px; height: 28px; border-radius: 4px; display: flex; align-items: center; justify-content: center; transition: 0.2s; }
            .btn-pagination:hover:not(:disabled) { background: #333; color: #fff; }
            .btn-pagination:disabled { opacity: 0.3; cursor: not-allowed; }

            .fade-in-up { animation: fadeInUp 0.6s ease-out; }
            @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        `}</style>
    </main>
  );
}
