'use client';
import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import MarketTicker from '@/components/MarketTicker';
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis 
} from 'recharts';

const BRAND_GOLD = '#FCD535';
const BG_DARK = '#1E1E1E';
const PANEL_BG = '#151515'; // لون أغمق قليلاً للكروت
const BORDER_COLOR = 'rgba(255, 255, 255, 0.08)'; // خطوط رفيعة جداً

// بيانات وهمية للشارت (سيتم ربطها لاحقاً)
const revenueData = [
  { name: 'Jan', revenue: 400 },
  { name: 'Feb', revenue: 1200 },
  { name: 'Mar', revenue: 900 },
  { name: 'Apr', revenue: 2400 },
  { name: 'May', revenue: 3800 },
  { name: 'Jun', revenue: 6500 },
];

const performanceData = [
  { subject: 'Clicks', A: 120, fullMark: 150 },
  { subject: 'Mints', A: 98, fullMark: 150 },
  { subject: 'Retention', A: 86, fullMark: 150 },
  { subject: 'Volume', A: 99, fullMark: 150 },
  { subject: 'Royalty', A: 85, fullMark: 150 },
  { subject: 'Activity', A: 65, fullMark: 150 },
];

export default function AffiliatePage() {
  const { address, isConnected } = useAccount();
  const [referralLink, setReferralLink] = useState('');
  const [isCopied, setIsCopied] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
      setMounted(true);
      if (address) {
          const origin = typeof window !== 'undefined' && window.location.origin ? window.location.origin : '';
          setReferralLink(`${origin}/mint?ref=${address}`);
      }
  }, [address]);

  const copyLink = () => {
      navigator.clipboard.writeText(referralLink);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
  };

  if (!mounted) return null;

  return (
    <main style={{ backgroundColor: '#050505', minHeight: '100vh', paddingBottom: '80px', color: '#fff', fontFamily: 'sans-serif' }}>
        
        {/* 1. TICKER (ملتصق بالنافبار) */}
        <div style={{ marginTop: '0px' }}>
            <MarketTicker />
        </div>

        {/* HERO SECTION */}
        <div className="container pt-5">
            <div className="row justify-content-center text-center mb-5">
                <div className="col-lg-10">
                    <h6 className="text-uppercase tracking-widest mb-3" style={{ color: '#666', letterSpacing: '3px', fontSize: '11px' }}>Institutional Partner Program</h6>
                    <h1 className="fw-bold mb-3" style={{ fontSize: '3rem', color: '#fff', letterSpacing: '-1px' }}>
                        NNM <span style={{ color: BRAND_GOLD }}>Alliance</span>
                    </h1>
                    <p style={{ color: '#999', maxWidth: '700px', margin: '0 auto', lineHeight: '1.6', fontSize: '15px' }}>
                        Build a sustainable revenue stream. Earn <span style={{ color: '#fff' }}>30% instant commission</span> on mints, plus <span style={{ color: '#fff' }}>10% lifetime royalties</span> on all future trading fees generated by your referred users.
                    </p>
                </div>
            </div>

            {!isConnected ? (
                <div className="d-flex justify-content-center align-items-center" style={{ height: '40vh' }}>
                    <div className="p-5 rounded-4 text-center" style={{ border: `1px solid ${BORDER_COLOR}`, background: PANEL_BG }}>
                        <i className="bi bi-wallet2 mb-3 d-block" style={{ fontSize: '30px', color: BRAND_GOLD }}></i>
                        <h3 className="h5 mb-4">Connect Wallet to Access Dashboard</h3>
                        <ConnectButton />
                    </div>
                </div>
            ) : (
                <div className="fade-in-up">
                    
                    {/* 2. REFERRAL LINK BAR */}
                    <div className="p-4 rounded-3 mb-5 d-flex flex-column flex-md-row align-items-center justify-content-between gap-4 glass-panel">
                        <div className="d-flex align-items-center gap-3 w-100">
                            <div className="icon-circle"><i className="bi bi-link-45deg"></i></div>
                            <div className="flex-grow-1">
                                <label style={{ fontSize: '10px', textTransform: 'uppercase', color: '#666', letterSpacing: '1px' }}>Your Exclusive Link</label>
                                <div className="d-flex align-items-center gap-2 mt-1">
                                    <code style={{ color: BRAND_GOLD, fontSize: '15px', background: 'transparent' }}>{referralLink}</code>
                                </div>
                            </div>
                        </div>
                        <button onClick={copyLink} className="btn-gold-outline">
                            {isCopied ? 'COPIED' : 'COPY LINK'}
                        </button>
                    </div>

                    {/* 3. KEY METRICS (STATS) */}
                    <div className="row g-3 mb-4">
                        {[
                            { label: "Total Revenue", value: "$6,500.00", icon: "bi-bank", trend: "+12%" },
                            { label: "Active Users", value: "142", icon: "bi-people", trend: "+5%" },
                            { label: "Assets Minted", value: "48", icon: "bi-diamond", trend: "+8%" },
                            { label: "Pending Payout", value: "$1,250.00", icon: "bi-wallet", trend: "Ready" }
                        ].map((stat, idx) => (
                            <div key={idx} className="col-md-3">
                                <div className="stat-card h-100">
                                    <div className="d-flex justify-content-between align-items-start mb-3">
                                        <div className="stat-icon"><i className={`bi ${stat.icon}`}></i></div>
                                        <span className="trend-badge">{stat.trend}</span>
                                    </div>
                                    <div className="stat-value">{stat.value}</div>
                                    <div className="stat-label">{stat.label}</div>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* 4. CHARTS SECTION (LUXURY VISUALIZATION) */}
                    <div className="row g-3 mb-5">
                        {/* Main Revenue Chart */}
                        <div className="col-lg-8">
                            <div className="chart-panel h-100">
                                <div className="panel-header">
                                    <h5 className="panel-title">Revenue Performance</h5>
                                    <div className="panel-actions">
                                        <span className="active">1M</span>
                                        <span>3M</span>
                                        <span>1Y</span>
                                    </div>
                                </div>
                                <div style={{ height: '300px', width: '100%' }}>
                                    <ResponsiveContainer width="100%" height="100%">
                                        <AreaChart data={revenueData}>
                                            <defs>
                                                <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                                                    <stop offset="5%" stopColor={BRAND_GOLD} stopOpacity={0.2}/>
                                                    <stop offset="95%" stopColor={BRAND_GOLD} stopOpacity={0}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#222" vertical={false} />
                                            <XAxis dataKey="name" stroke="#555" fontSize={11} tickLine={false} axisLine={false} />
                                            <YAxis stroke="#555" fontSize={11} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} />
                                            <Tooltip 
                                                contentStyle={{ backgroundColor: '#111', border: `1px solid ${BORDER_COLOR}`, borderRadius: '8px' }}
                                                itemStyle={{ color: BRAND_GOLD }}
                                            />
                                            <Area type="monotone" dataKey="revenue" stroke={BRAND_GOLD} strokeWidth={2} fillOpacity={1} fill="url(#colorRev)" />
                                        </AreaChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                        </div>

                        {/* Radar Chart (The "Circle with Triangles") */}
                        <div className="col-lg-4">
                            <div className="chart-panel h-100">
                                <div className="panel-header mb-4">
                                    <h5 className="panel-title">Ecosystem Impact</h5>
                                </div>
                                <div style={{ height: '260px', width: '100%', position: 'relative' }}>
                                    <ResponsiveContainer width="100%" height="100%">
                                        <RadarChart cx="50%" cy="50%" outerRadius="80%" data={performanceData}>
                                            <PolarGrid stroke="#333" />
                                            <PolarAngleAxis dataKey="subject" tick={{ fill: '#888', fontSize: 10 }} />
                                            <PolarRadiusAxis angle={30} domain={[0, 150]} tick={false} axisLine={false} />
                                            <Radar
                                                name="My Performance"
                                                dataKey="A"
                                                stroke={BRAND_GOLD}
                                                strokeWidth={2}
                                                fill={BRAND_GOLD}
                                                fillOpacity={0.3}
                                            />
                                        </RadarChart>
                                    </ResponsiveContainer>
                                    {/* Center Glow */}
                                    <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '10px', height: '10px', background: BRAND_GOLD, borderRadius: '50%', boxShadow: `0 0 20px 5px ${BRAND_GOLD}44` }}></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* 5. DATA TABLE (THE "LEDGER") */}
                    <div className="chart-panel">
                        <div className="panel-header mb-3">
                            <h5 className="panel-title">Transaction Ledger</h5>
                            <button className="btn-icon"><i className="bi bi-download"></i> CSV</button>
                        </div>
                        <div className="table-responsive">
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th>TIMESTAMP</th>
                                        <th>TYPE</th>
                                        <th>WALLET</th>
                                        <th>ASSET</th>
                                        <th>AMOUNT</th>
                                        <th className="text-end">YOUR CUT (10%)</th>
                                        <th className="text-end">STATUS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {[1, 2, 3, 4].map((_, i) => (
                                        <tr key={i}>
                                            <td style={{ color: '#666' }}>2025-01-1{i} 14:30</td>
                                            <td><span className="type-badge">MINT</span></td>
                                            <td style={{ fontFamily: 'monospace', color: '#888' }}>0x71C...9A2{i}</td>
                                            <td>NNM #{1020 + i}</td>
                                            <td>$50.00</td>
                                            <td className="text-end" style={{ color: BRAND_GOLD, fontWeight: 'bold' }}>+$15.00</td>
                                            <td className="text-end"><span className="status-badge success">PAID</span></td>
                                        </tr>
                                    ))}
                                    {/* Example of Secondary Sale Royalty */}
                                    <tr>
                                        <td style={{ color: '#666' }}>2025-01-15 09:12</td>
                                        <td><span className="type-badge secondary">TRADE</span></td>
                                        <td style={{ fontFamily: 'monospace', color: '#888' }}>0x33B...1F4</td>
                                        <td>NNM #888</td>
                                        <td>$200.00</td>
                                        <td className="text-end" style={{ color: BRAND_GOLD, fontWeight: 'bold' }}>+$20.00</td>
                                        <td className="text-end"><span className="status-badge pending">PENDING</span></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            )}
        </div>

        <style jsx>{`
            .glass-panel {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                box-shadow: 0 4px 20px rgba(0,0,0,0.2);
            }
            .icon-circle {
                width: 40px; height: 40px;
                border-radius: 50%;
                background: rgba(252, 213, 53, 0.1);
                color: ${BRAND_GOLD};
                display: flex; align-items: center; justify-content: center;
                font-size: 18px;
            }
            .btn-gold-outline {
                background: transparent;
                border: 1px solid ${BRAND_GOLD};
                color: ${BRAND_GOLD};
                padding: 10px 24px;
                border-radius: 6px;
                font-size: 12px;
                font-weight: 700;
                letter-spacing: 1px;
                transition: all 0.3s;
            }
            .btn-gold-outline:hover {
                background: ${BRAND_GOLD};
                color: #000;
                box-shadow: 0 0 15px rgba(252, 213, 53, 0.3);
            }

            /* Stats Cards */
            .stat-card {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                border-radius: 12px;
                padding: 20px;
                position: relative;
                overflow: hidden;
            }
            .stat-card::before {
                content: ''; position: absolute; top: 0; left: 0; width: 2px; height: 100%;
                background: ${BRAND_GOLD}; opacity: 0.5;
            }
            .stat-icon { color: #444; font-size: 20px; }
            .stat-value { font-size: 24px; font-weight: 700; color: #fff; margin-bottom: 5px; font-family: 'Inter', sans-serif; }
            .stat-label { font-size: 11px; text-transform: uppercase; color: #666; letter-spacing: 1px; }
            .trend-badge { font-size: 10px; color: #4caf50; background: rgba(76, 175, 80, 0.1); padding: 2px 6px; border-radius: 4px; }

            /* Charts Panels */
            .chart-panel {
                background: ${PANEL_BG};
                border: 1px solid ${BORDER_COLOR};
                border-radius: 12px;
                padding: 20px;
            }
            .panel-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid ${BORDER_COLOR}; padding-bottom: 15px; margin-bottom: 15px; }
            .panel-title { font-size: 14px; color: #fff; margin: 0; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
            .panel-actions span { font-size: 11px; color: #666; cursor: pointer; margin-left: 15px; transition: 0.2s; }
            .panel-actions span.active { color: ${BRAND_GOLD}; font-weight: bold; }
            
            /* Table Styling */
            .table { margin: 0; }
            .table th { background: transparent; color: #555; font-size: 10px; font-weight: 600; letter-spacing: 1px; border-bottom: 1px solid #333; padding-bottom: 15px; }
            .table td { background: transparent; color: #ddd; font-size: 13px; border-bottom: 1px solid #222; padding: 15px 0; vertical-align: middle; }
            .table tr:last-child td { border-bottom: none; }
            
            .type-badge { font-size: 9px; padding: 3px 8px; border-radius: 4px; font-weight: bold; background: #222; color: #888; border: 1px solid #333; }
            .type-badge.secondary { background: rgba(56, 189, 248, 0.1); color: #38BDF8; border-color: rgba(56, 189, 248, 0.2); }
            
            .status-badge { font-size: 9px; padding: 3px 8px; border-radius: 4px; font-weight: bold; }
            .status-badge.success { color: #4caf50; background: rgba(76, 175, 80, 0.1); }
            .status-badge.pending { color: #ff9800; background: rgba(255, 152, 0, 0.1); }

            .btn-icon { background: transparent; border: 1px solid #333; color: #888; border-radius: 4px; padding: 4px 10px; font-size: 11px; }
            .btn-icon:hover { border-color: #666; color: #fff; }

            .fade-in-up { animation: fadeInUp 0.6s ease-out; }
            @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        `}</style>
    </main>
  );
}
